# Build de Astro + servidor estático (serve) en una imagen Node.
FROM node:22-bookworm-slim

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY astro.config.mjs tsconfig.json ./
COPY public ./public
COPY src ./src
COPY scripts ./scripts

# Variables PUBLIC_* (analítica, anuncios, formulario): en Railway se declaran en Variables y
# se pasan al build. Vacías = no se carga ninguna etiqueta. Ver .env.example.
ARG PUBLIC_GTM_ID=""
ARG PUBLIC_GA4_ID=""
ARG PUBLIC_GADS_ID=""
ARG PUBLIC_GADS_LEAD_LABEL=""
ARG PUBLIC_META_PIXEL_ID=""
ARG PUBLIC_TIKTOK_PIXEL_ID=""
ARG PUBLIC_LINKEDIN_PARTNER_ID=""
ARG PUBLIC_LINKEDIN_LEAD_CONVERSION_ID=""
ARG PUBLIC_BING_UET_ID=""
ARG PUBLIC_FORM_ENDPOINT=""
ARG PUBLIC_GSC_VERIFICATION=""
ARG PUBLIC_BING_VERIFICATION=""
ARG PUBLIC_META_DOMAIN_VERIFICATION=""
ARG PUBLIC_TIKTOK_VERIFICATION=""
ARG PUBLIC_PINTEREST_VERIFICATION=""
ENV PUBLIC_GTM_ID=$PUBLIC_GTM_ID \
    PUBLIC_GA4_ID=$PUBLIC_GA4_ID \
    PUBLIC_GADS_ID=$PUBLIC_GADS_ID \
    PUBLIC_GADS_LEAD_LABEL=$PUBLIC_GADS_LEAD_LABEL \
    PUBLIC_META_PIXEL_ID=$PUBLIC_META_PIXEL_ID \
    PUBLIC_TIKTOK_PIXEL_ID=$PUBLIC_TIKTOK_PIXEL_ID \
    PUBLIC_LINKEDIN_PARTNER_ID=$PUBLIC_LINKEDIN_PARTNER_ID \
    PUBLIC_LINKEDIN_LEAD_CONVERSION_ID=$PUBLIC_LINKEDIN_LEAD_CONVERSION_ID \
    PUBLIC_BING_UET_ID=$PUBLIC_BING_UET_ID \
    PUBLIC_FORM_ENDPOINT=$PUBLIC_FORM_ENDPOINT \
    PUBLIC_GSC_VERIFICATION=$PUBLIC_GSC_VERIFICATION \
    PUBLIC_BING_VERIFICATION=$PUBLIC_BING_VERIFICATION \
    PUBLIC_META_DOMAIN_VERIFICATION=$PUBLIC_META_DOMAIN_VERIFICATION \
    PUBLIC_TIKTOK_VERIFICATION=$PUBLIC_TIKTOK_VERIFICATION \
    PUBLIC_PINTEREST_VERIFICATION=$PUBLIC_PINTEREST_VERIFICATION

RUN npx astro build && npm prune --omit=dev && chmod +x scripts/railway-start.sh

# Project ID de Clarity (sobreescribible en Variables de Railway).
ENV CLARITY_PROJECT_ID=ylu80felfk
ENV NODE_ENV=production
ENV PORT=3000

EXPOSE 3000

CMD ["bash", "scripts/railway-start.sh"]
